# Generated by Django 5.2.8 on 2025-11-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.TextField(blank=True)),
                ('calories', models.IntegerField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.PositiveIntegerField()),
                ('total_calories', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.mealplan')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.mealplan'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('activity', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (1-3 days/week)'), ('moderate', 'Moderately active (3-5 days/week)'), ('active', 'Very active (6-7 days/week)'), ('very_active', 'Extra active (physical job or training)')], default='sedentary', max_length=20)),
                ('goal', models.CharField(choices=[('lose', 'Lose weight'), ('maintain', 'Maintain weight'), ('gain', 'Gain weight')], default='maintain', max_length=10)),
                ('dietary_pref', models.CharField(blank=True, help_text='e.g. vegetarian, vegan, omnivore', max_length=50)),
                ('allergies', models.CharField(blank=True, help_text='comma separated, e.g. peanuts,gluten', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
