# Generated by Django 5.2.8 on 2025-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_pref',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
