# Generated by Django 5.2.8 on 2025-11-26 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_remove_userprofile_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (1-3 days/week)'), ('moderate', 'Moderately active (3-5 days/week)'), ('active', 'Very active (6-7 days/week)'), ('very_active', 'Extra active (physical job or training)')], default='sedentary', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, default='', help_text='comma-separated, e.g. peanuts,gluten', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_pref',
            field=models.CharField(blank=True, default='', help_text='e.g. vegetarian, vegan', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose weight'), ('maintain', 'Maintain weight'), ('gain', 'Gain weight')], default='maintain', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs_g',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat_g',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein_g',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='slot',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack1', 'Snack 1'), ('snack2', 'Snack 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='total_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
